### ISSUE TITLE
Problem with launch script

### ISSUE THREAD

**Issue by pfotouhi** [darchr/gpu-fs-experiments#3]
@ayaz91 
Can you please take a look at this?
I'm getting the following and I don't really know where I messed up.

'
Traceback (most recent call last):
  File "launch_gpu-fs.py", line 112, in <module>
    timeout = 6*60*60 #6 hours
  File "/fasthome/pfotouhi/gpu-fs-experiments/venv/lib/python3.6/site-packages/gem5art/run.py", line 237, in createFSRun
    timeout)
  File "/fasthome/pfotouhi/gpu-fs-experiments/venv/lib/python3.6/site-packages/gem5art/run.py", line 123, in _create
    run.outdir = os.path.abspath(outdir)
  File "/fasthome/pfotouhi/gpu-fs-experiments/venv/lib/python3.6/posixpath.py", line 378, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not Artifact
'

**Comment by aakahlow** [comment]
Hi @pfotouhi : I have pushed some pending updates to the documentation. If you look at the updated Run section (https://gem5art.readthedocs.io/en/latest/main-doc/run.html#se-and-fs-mode-runs), you will see that there is a new argument `name` for the createFS/SERun, which is supposed to be a tag which can be used to find particular runs in the database. You also need to pass the cwd to run_gem5_instance() call. Please, have a look at the updated launch scripts for boot experiments (https://github.com/darchr/gem5art/blob/master/docs/launch-scripts/launch_boot_tests.py).

**Comment by pfotouhi** [comment]
Thanks @ayaz91 , much appreciated! I'll do accordingly and bother you again if I happen to be stuck again.
